spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/distove_db
    username: root
    password: lee-120807
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
